id: P18876999
initial_creation_type: ocr
source_metadata:
  volumes:
    535d1d0819704c829cb358db5d81da42:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: རྒྱུད་ཀྱི་རྒྱལ་པོ་དཔལ་གདན་བཞི་པ་ཞེས་བྱ་བའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག་སྙིང་པོ་མདོར་བསགས་པ།
      total_pages: 2043
      volume_number: 13
